[source]
type = "N2N"
address = "relays-new.cardano-mainnet.iohk.io:3001"

[[reducers]]
type = "AddressByAdaHandle"
policy_id_hex = "f0ff48bbb7bbe9d59a40f1ce90e9e9d0ff5002ec48f232b49ca0fb9a"

[storage]
type = "Redis"
connection_params = "redis://redis:6379"

[chain]
type = "Mainnet"

# mainnet intersection point
[intersect]
# type = "Origin"
type = "Point"
value = [66719257, "701fceedbd279d04d4c958f693bc7a85ace679d878c355edffbfdcd6bf631de0"]