[source]
type = "N2N"
address = "relays-new.cardano-mainnet.iohk.io:3001"

[[reducers]]
type = "AddressByAdaHandle"
policy_id_hex = "f0ff48bbb7bbe9d59a40f1ce90e9e9d0ff5002ec48f232b49ca0fb9a"

[storage]
type = "Redis"
connection_params = "redis://redis:6379"

[chain]
type = "Mainnet"

# mainnet intersection point
[intersect]
# type = "Origin"
type = "Point"
value = [47931333, "847543d30b99cbb288bee3064f83ff50140cf944ce60fa5d356f27611e94b1f0"]

# # preprod intersection point
# [intersect]
# type = "Point"
# value = [5861832, "66db4adde5190d3d971228b4718e1a56100856d4c65ae271e26cc4152ef341a7"]