version: '3.7'

services:
  # proxy:
  #   image: nginx:alpine
  #   container_name: proxy
  #   ports:
  #     - '4040:4040'
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   restart: 'unless-stopped'
  #   networks:
  #     - backend
  server:
    build:
      context: ./
      target: production-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '4040:4040'
    volumes:
      - ./:/app
      - /app/node_modules
    links:
      - redis
    depends_on:
      - redis
    environment:
    - REDIS_URL=redis://redis
    - LOG_DIR=logs
    # - PORT=4040 configured by .env.production.local
    restart: 'unless-stopped'
    networks:
      - backend
  scrolls:
    image: ghcr.io/txpipe/scrolls:v0.4.2
    command: [ "daemon" ]
    environment:
      - RUST_LOG=info
    volumes:
      - ./daemon.toml:/etc/scrolls/daemon.toml
    links:
      - redis
    networks:
      - backend
  redis:
    image: redis
    volumes:
      - ./data:/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
